feat : 고객서비스센터 ui 임시 구현
p-ser/p-ser-frontend pull request #4
Opened 2024-04-22 17:22 UTC by wooyong99

### 개요
- 고객 서비스 센터 UI  임시 구현
<img width="809" alt="image" src="https://github.com/p-ser/p-ser-frontend/assets/85385921/ba7e64d4-64bf-4b19-97f8-297c083c277b">

### 변경사항
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KSP-136](https://kakaoproject3.atlassian.net/browse/KSP-136)

### 팀원들에게 하고 싶은 말
- 해당 UI 구현하는데 있어서, 아코디언 메뉴는 정상작동하도록 구현하였습니다.
Font 부분에서 기존 Font와 불일치하는 현상 해결이 안되서.. 우선적으로 PR 올려두도록 하겠습니다 !
아직 임시 구현이라 리뷰 남겨주시면 리팩토링 후 mege 진행하겠습니다.

2024-04-24 01:27 UTC, amanecopse approved these changes

2024-05-02 04:29 UTC, chanhyuk0919 approved these changes
확인 했습니다

2024-05-13 00:14 UTC, amanecopse requested changes
.

2024-05-13 00:14 UTC, amanecopse approved these changes

2024-05-16 05:58 UTC, merged